//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{


    public partial class Deportes
    {

        /// <summary>
        /// lblTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotal;

        /// <summary>
        /// btnNuevo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>
        /// pnlConfirmarBaja control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlConfirmarBaja;

        /// <summary>
        /// lblConfirmarBaja control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblConfirmarBaja;

        /// <summary>
        /// btnConfirmarBaja control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarBaja;

        /// <summary>
        /// btnCancelarBaja control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelarBaja;

        /// <summary>
        /// hfBajaId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfBajaId;

        /// <summary>
        /// rptDeportes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptDeportes;

        /// <summary>
        /// lblTituloModalDeporte control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTituloModalDeporte;

        /// <summary>
        /// hfIdDeporte control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfIdDeporte;

        /// <summary>
        /// lblErrorDeporte control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorDeporte;

        /// <summary>
        /// txtNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>
        /// rfvNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;

        /// <summary>
        /// txtDuracion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDuracion;

        /// <summary>
        /// rfvDuracion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDuracion;

        /// <summary>
        /// rvDuracion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvDuracion;

        /// <summary>
        /// btnGuardarDeporte control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardarDeporte;
    }
}
