//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{


    public partial class Reservas
    {

        /// <summary>
        /// ddlFiltroEstado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroEstado;

        /// <summary>
        /// ddlFiltroCancha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroCancha;

        /// <summary>
        /// txtFiltroFecha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFiltroFecha;

        /// <summary>
        /// btnFiltrar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>
        /// btnLimpiar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>
        /// lblTotal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotal;

        /// <summary>
        /// lblErrorFinalizar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblErrorFinalizar;

        /// <summary>
        /// rptReservas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptReservas;

        /// <summary>
        /// lblDetCliente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetCliente;

        /// <summary>
        /// lblDetCancha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetCancha;

        /// <summary>
        /// lblDetFecha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetFecha;

        /// <summary>
        /// lblDetHorario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetHorario;

        /// <summary>
        /// lblDetPrecio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetPrecio;

        /// <summary>
        /// lblDetEstado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetEstado;

        /// <summary>
        /// lblDetPago control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetPago;

        /// <summary>
        /// lblDetPagado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetPagado;

        /// <summary>
        /// lblDetSaldo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetSaldo;

        /// <summary>
        /// lblDetObs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetObs;

        /// <summary>
        /// lblPagosReserva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPagosReserva;

        /// <summary>
        /// lblPagosPrecio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPagosPrecio;

        /// <summary>
        /// lblPagosPagado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPagosPagado;

        /// <summary>
        /// lblPagosSaldo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPagosSaldo;

        /// <summary>
        /// rptPagos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPagos;

        /// <summary>
        /// lblPagosVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPagosVacio;

        /// <summary>
        /// hfIdReservaPago control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfIdReservaPago;

        /// <summary>
        /// lblErrorPago control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblErrorPago;

        /// <summary>
        /// lblPagoReserva control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPagoReserva;

        /// <summary>
        /// lblPagoPrecio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPagoPrecio;

        /// <summary>
        /// lblPagoPagado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPagoPagado;

        /// <summary>
        /// lblPagoSaldo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPagoSaldo;

        /// <summary>
        /// txtMontoPago control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtMontoPago;

        /// <summary>
        /// ddlFormaPago control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFormaPago;

        /// <summary>
        /// btnConfirmarPago control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnConfirmarPago;

        /// <summary>
        /// hfIdReservaCanje control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfIdReservaCanje;

        /// <summary>
        /// lblErrorCanje control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblErrorCanje;

        /// <summary>
        /// lblCanjeReserva control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCanjeReserva;

        /// <summary>
        /// lblCanjePrecio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCanjePrecio;

        /// <summary>
        /// txtCodigoCupon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCodigoCupon;

        /// <summary>
        /// btnConfirmarCanje control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnConfirmarCanje;

        /// <summary>
        /// hfIdReservaCancelacion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfIdReservaCancelacion;

        /// <summary>
        /// lblErrorCancelacion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblErrorCancelacion;

        /// <summary>
        /// lblCancelacionReserva control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCancelacionReserva;

        /// <summary>
        /// lblCancelacionCliente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCancelacionCliente;

        /// <summary>
        /// lblCancelacionFecha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCancelacionFecha;

        /// <summary>
        /// lblCancelacionPrecio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCancelacionPrecio;

        /// <summary>
        /// btnConfirmarCancelacion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnConfirmarCancelacion;

        /// <summary>
        /// hfIdReservaFinalizar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfIdReservaFinalizar;

        /// <summary>
        /// hfIdClienteFinalizar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfIdClienteFinalizar;

        /// <summary>
        /// pnlCuponGanado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCuponGanado;

        /// <summary>
        /// lblCuponGanado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCuponGanado;

        /// <summary>
        /// lblResultadoCuponIcono control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultadoCuponIcono;

        /// <summary>
        /// lblResultadoCuponTitulo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultadoCuponTitulo;

        /// <summary>
        /// lblResultadoCuponMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultadoCuponMsg;

        /// <summary>
        /// lblResultadoCuponPrecio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultadoCuponPrecio;

        /// <summary>
        /// lblFinalizarReserva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFinalizarReserva;

        /// <summary>
        /// lblFinalizarCliente control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFinalizarCliente;

        /// <summary>
        /// lblFinalizarFecha control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFinalizarFecha;

        /// <summary>
        /// lblFinalizarPrecio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFinalizarPrecio;

        /// <summary>
        /// btnConfirmarFinalizar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarFinalizar;

        /// <summary>
        /// upReprogramar control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel upReprogramar;

        /// <summary>
        /// hfIdReservaReprogramar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfIdReservaReprogramar;

        /// <summary>
        /// hfIdCanchaReprogramar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfIdCanchaReprogramar;

        /// <summary>
        /// lblErrorReprogramar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorReprogramar;

        /// <summary>
        /// lblReprogramarReserva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReprogramarReserva;

        /// <summary>
        /// lblReprogramarCliente control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReprogramarCliente;

        /// <summary>
        /// lblReprogramarCancha control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReprogramarCancha;

        /// <summary>
        /// lblReprogramarActual control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReprogramarActual;

        /// <summary>
        /// txtFechaReprogramar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaReprogramar;

        /// <summary>
        /// ddlHorarioReprogramar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlHorarioReprogramar;

        /// <summary>
        /// lblSinHorariosReprog control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSinHorariosReprog;

        /// <summary>
        /// btnConfirmarReprogramar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarReprogramar;

        /// <summary>
        /// upPagoOnline control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel upPagoOnline;

        /// <summary>
        /// hfIdReservaOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfIdReservaOnline;

        /// <summary>
        /// pnlFormularioOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormularioOnline;

        /// <summary>
        /// lblErrorOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorOnline;

        /// <summary>
        /// lblOnlineReserva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOnlineReserva;

        /// <summary>
        /// lblOnlinePrecio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOnlinePrecio;

        /// <summary>
        /// lblOnlinePagado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOnlinePagado;

        /// <summary>
        /// lblOnlineSaldo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOnlineSaldo;

        /// <summary>
        /// txtMontoOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMontoOnline;

        /// <summary>
        /// ddlMetodoOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMetodoOnline;

        /// <summary>
        /// pnlTarjetaOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTarjetaOnline;

        /// <summary>
        /// txtTitular control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitular;

        /// <summary>
        /// rfvTitular control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitular;

        /// <summary>
        /// txtNumeroTarjeta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNumeroTarjeta;

        /// <summary>
        /// rfvNumero control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNumero;

        /// <summary>
        /// revNumero control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revNumero;

        /// <summary>
        /// txtVencimiento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtVencimiento;

        /// <summary>
        /// rfvVencimiento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvVencimiento;

        /// <summary>
        /// revVencimiento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revVencimiento;

        /// <summary>
        /// txtCvv control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCvv;

        /// <summary>
        /// rfvCvv control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCvv;

        /// <summary>
        /// revCvv control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revCvv;

        /// <summary>
        /// pnlMercadoPagoOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMercadoPagoOnline;

        /// <summary>
        /// pnlExitoOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlExitoOnline;

        /// <summary>
        /// lblExitoOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblExitoOnline;

        /// <summary>
        /// btnConfirmarPagoOnline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarPagoOnline;

        /// <summary>
        /// upNuevaReserva control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel upNuevaReserva;

        /// <summary>
        /// lblErrorNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorNueva;

        /// <summary>
        /// pnlClienteNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlClienteNueva;

        /// <summary>
        /// ddlClienteNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlClienteNueva;

        /// <summary>
        /// ddlCanchaNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCanchaNueva;

        /// <summary>
        /// txtFechaNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaNueva;

        /// <summary>
        /// txtPrecioNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrecioNueva;

        /// <summary>
        /// lblAyudaPrecio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAyudaPrecio;

        /// <summary>
        /// pnlSugeridos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSugeridos;

        /// <summary>
        /// rptSugeridos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSugeridos;

        /// <summary>
        /// ddlHorarioNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlHorarioNueva;

        /// <summary>
        /// lblSinHorarios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSinHorarios;

        /// <summary>
        /// txtObservacionesNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtObservacionesNueva;

        /// <summary>
        /// txtCuponNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCuponNueva;

        /// <summary>
        /// lblAyudaCupon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAyudaCupon;

        /// <summary>
        /// btnGuardarReserva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardarReserva;
    }
}
